version: '3'
services:
  redis:
    build: ./redis
    ports:
      - 6380:6379
    environment:
      - VIRTUAL_HOST=redis.test
      - NETWORK_ACCESS=internal
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - 27016:27017
    environment:
      - NETWORK_ACCESS=internal
  ldap:
    build: ./ldap
    ports:
      - 1390:1389
    volumes:
      - ./ldap/app:/home/node/app
    environment:
      - VIRTUAL_HOST=ldap.localhost
      - NETWORK_ACCESS=internal
  php5:
    build: ./php5
    ports:
      - 8001:80
    volumes:
      - ./php5/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site1.test
      - NETWORK_ACCESS=internal
  php7:
    build: ./php7
    ports:
      - 8002:80
    volumes:
      - ./php7/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site2.test,site3.test
      - NETWORK_ACCESS=internal
  phpmyadmin:
    build: ./phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8000:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=pma.localhost
      - NETWORK_ACCESS=internal
  apache-python3:
    build: ./apache-python3
    ports:
      - 8001:80
    volumes:
      - ./apache-python3/sites:/var/www/html
      - ./apache-python3/sites-available:/etc/apache2/sites-available
    environment:
      - VIRTUAL_HOST=casino.test
      - NETWORK_ACCESS=internal
  mariadb:
    build: ./mariadb
    ports:
      - 3305:3306
    volumes:
      - ./mariadb/data/persistent:/var/lib/mysql
      - ./mariadb/data/init:/docker-entrypoint-initdb.d
      - ./mariadb/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=mariadb.test
      - NETWORK_ACCESS=internal
networks:
  default:
    external:
      name: nginxproxy_default
