version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./nginx/network_internal.conf:/etc/nginx/network_internal.conf:ro
networks:
  default:
    external:
      name: nginxproxy_default
