version: '3'
services:
  redis:
    build: ./redis
    user: ${DEV_UID:-1000}:${DEV_GID:-100}
    ports:
      - 6380:6379
    environment:
      - VIRTUAL_HOST=redis.test
      - NETWORK_ACCESS=internal
    volumes:
      - ./redis/data:/data
  mongodb:
    build: ./mongodb
    ports:
      - 27016:27017
    environment:
      - NETWORK_ACCESS=internal
  ldap:
    build: ./ldap
    ports:
      - 1390:1389
    volumes:
      - ./ldap/app:/home/node/app
    environment:
      - VIRTUAL_HOST=ldap.test
      - NETWORK_ACCESS=internal
  php5:
    build: ./php5
    ports:
      - 8001:80
    volumes:
      - ./php5/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site1.test
      - NETWORK_ACCESS=internal
  php7:
    build: ./php7
    ports:
      - 8002:80
    volumes:
      - ./php7/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site2.test,site3.test
      - NETWORK_ACCESS=internal
  phpmyadmin:
    build: ./phpmyadmin
    user: ${DEV_UID:-1000}:${DEV_GID:-100}
    links:
      - mariadb:db
    ports:
      - 8000:8123
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=pma.test
      - NETWORK_ACCESS=internal
  apache-python3:
    build: ./apache-python3
    user: ${DEV_UID:-1000}:${DEV_GID:-100}
    ports:
      - 8003:80
      - 8004:443
    volumes:
      - ./apache-python3/sites:/var/www/html
      - ./apache-python3/sites-available:/etc/apache2/sites-available
    environment:
      - VIRTUAL_HOST=casino.test
      - NETWORK_ACCESS=internal
      - PACMAN_PACKAGES=${DAS_APACHEPYTHON3_PACMAN_PACKAGES}
      - PIP_PACKAGES=${DAS_APACHEPYTHON3_PIP_PACKAGES}
  mariadb:
    build: ./mariadb
    user: ${DEV_UID:-1000}:${DEV_GID:-100}
    ports:
      - 3305:3306
    volumes:
      - ./mariadb/data/persistent:/var/lib/mysql
      - ./mariadb/data/init:/docker-entrypoint-initdb.d
      - ./mariadb/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=mariadb.test
      - NETWORK_ACCESS=internal
  crossbar:
    build: ./crossbar
    user: ${DEV_UID:-1000}:${DEV_GID:-100}
    tty: true
    ports:
      - 8081:8080
    volumes:
      - ./crossbar/node:/node
    environment:
      - VIRTUAL_HOST=crossbar.test
      - NETWORK_ACCESS=internal
      - PIP_PACKAGES=${DAS_CROSSBAR_PIP_PACKAGES}
networks:
  default:
    external:
      name: nginxproxy_default
