version: '2'
services:
  redis:
    image: redis:3.0.7
    ports:
      - 6379
    environment:
      - VIRTUAL_HOST=redis.dev
  mysql:
    image: mysql:5.7
    ports:
      - 3306
    volumes:
      - /var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=secretpass
      - VIRTUAL_HOST=mysql.dev
  php5.6:
    build: ./php5.6
    ports:
      - 8001:80
    volumes:
      - ./php5.6/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site1.dev
  php7.1:
    build: ./php7.1
    ports:
      - 8002:80
    volumes:
      - ./php7.1/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site2.dev,site3.dev
networks:
  default:
    external:
      name: nginxproxy_default
