version: '3'
services:
  redis:
    image: redis:3.2
    ports:
      - 6380:6379
    environment:
      - VIRTUAL_HOST=redis.dev
      - NETWORK_ACCESS=internal
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - 27016:27017
    environment:
      - NETWORK_ACCESS=internal
  ldap:
    build: ./ldap
    ports:
      - 1390:1389
    volumes:
      - ./ldap/app:/home/node/app
    environment:
      - VIRTUAL_HOST=ldap.localhost
      - NETWORK_ACCESS=internal
  mysql:
    image: mysql:5.7
    ports:
      - 3305:3306
    volumes:
      - ./mysql/data/persistent:/var/lib/mysql
      - ./mysql/data/init:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpass
      - VIRTUAL_HOST=mysql.dev
      - NETWORK_ACCESS=internal
  php5.6:
    build: ./php5.6
    ports:
      - 8001:80
    volumes:
      - ./php5.6/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site1.dev
      - NETWORK_ACCESS=internal
  php7.1:
    build: ./php7.1
    ports:
      - 8002:80
    volumes:
      - ./php7.1/src:/var/www/html
    environment:
      - VIRTUAL_HOST=site2.dev,site3.dev
  apache-python3:
    build: ./apache-python3
    ports:
      - 8001:80
    volumes:
      - ./apache-python3/sites:/var/www/html
      - ./apache-python3/sites-available:/etc/apache2/sites-available
    environment:
      - VIRTUAL_HOST=casino.test
      - NETWORK_ACCESS=internal
  mariadb:
    build: ./mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - NETWORK_ACCESS=internal
    volumes:
      - ./mariadb/data/persistent:/var/lib/mysql
      - ./mariadb/data/init:/docker-entrypoint-initdb.d
networks:
  default:
    external:
      name: nginxproxy_default
